export const DEFAULT_CKEDITOR_TOOLBAR: any[] = [
  {
    name: 'document',
    items: [
      'Source',
      '-',
      'Save',
      'NewPage',
      'DocProps',
      'Preview',
      'Print',
      '-',
      'Templates',
    ],
  },
  {
    name: 'clipboard',
    items: [
      'Cut',
      'Copy',
      'Paste',
      'PasteText',
      'PasteFromWord',
      '-',
      'Undo',
      'Redo',
    ],
  },
  {
    name: 'editing',
    items: [
      'Find',
      'Replace',
      '-',
      'SelectAll',
      '-',
      'SpellChecker',
      'Scayt',
    ],
  },
  {
    name: 'forms',
    items: [
      'Form',
      'Checkbox',
      'Radio',
      'TextField',
      'Textarea',
      'Select',
      'Button',
      'ImageButton',
      'HiddenField',
    ],
  },
  '/',
  {
    name: 'basicstyles',
    items: [
      'Bold',
      'Italic',
      'Underline',
      'Strike',
      'Subscript',
      'Superscript',
      '-',
      'RemoveFormat',
      'CopyFormatting',
    ],
  },
  {
    name: 'paragraph',
    items: [
      'NumberedList',
      'BulletedList',
      '-',
      'Outdent',
      'Indent',
      '-',
      'Blockquote',
      'CreateDiv',
      '-',
      'JustifyLeft',
      'JustifyCenter',
      'JustifyRight',
      'JustifyBlock',
      '-',
      'BidiLtr',
      'BidiRtl',
      'Language',
    ],
  },
  { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
  {
    name: 'insert',
    items: [
      'Image',
      'Flash',
      'Table',
      'HorizontalRule',
      'Smiley',
      'SpecialChar',
      'PageBreak',
      'Iframe',
    ],
  },
  '/',
  { name: 'styles', items: ['Styles', 'Format', 'Font', 'FontSize'] },
  { name: 'colors', items: ['TextColor', 'BGColor'] },
  { name: 'tools', items: ['Maximize', 'ShowBlocks'] },
  {
    name: 'customTools',
    items: ['CustomImage', 'InsertTableTemplate', 'NextPage', 'PickrBgColor'],
  },
]

